name: astro-deployment

on:
  release:
    tags:
      - v*

env:
  DOCKER_IMAGE_NAME: byeweb-frontend

jobs:
  create_docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  push_docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build . --file --tag $DOCKER_IMAGE_NAME
    - name: Log into docker registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

